services:
  trading_bot:
    build: .
    container_name: my_trading_bot_container
    env_file: # 이 부분을 추가해주세요
      - .env  # 프로젝트 루트에 있는 .env 파일을 읽어 환경변수로 설정합니다.
    volumes:
      - ./src:/app
      - ./config:/app/config
      - ./output:/app/output
    restart: always
    command: sleep infinity