# 이 스택 전체의 프로젝트/리소스 이름 접두사
name: isa_stack

x-common: &common
  build:
    context: .           # Dockerfile이 isa/ 폴더 안에 있으면 이대로
    # dockerfile: ../Dockerfile   # 만약 루트에 Dockerfile이 있다면 주석 해제
  restart: always
  volumes:
    - ./src:/app/src

services:
  # 스케줄에 따라 전체 파이프라인 실행
  scheduler:
    <<: *common
    container_name: isa_my_trading_bot_scheduler
    env_file:
      - ./config/.env        # isa/config/.env
    volumes:
      - ./src:/app/src
      - ./config:/app/config # isa/config -> /app/config
      - ./output:/app/output # isa/output -> /app/output
    command: python /app/src/scheduler.py

  # 보유 종목 실시간 모니터링
  risk_manager:
    <<: *common
    container_name: isa_my_trading_bot_risk_manager
    env_file:
      - ./config/.env
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./output:/app/output
    command: python /app/src/risk_manager.py
