version: '3.8'

services:
  trading_bot:
    build: .
    container_name: my_trading_bot_container
    volumes:
      - ./src:/app
      - ./config:/app/config
    restart: always
    # ⬇️ 이 부분을 추가해주세요.
    # 이 명령은 Dockerfile의 CMD를 덮어쓰고,
    # 컨테이너가 꺼지지 않고 계속 대기하도록 만듭니다.
    command: sleep infinity